spring.application.name=task-manager-kanban


# Servidor
server.port=${PORT:10000}
server.address=0.0.0.0
server.error.include-message=always

# Base de Datos (Inyectado desde Render Environment)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.data-source-properties.sslmode=require

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT (ESTO ES LO QUE FALTABA)
app.jwt.secret=${APP_JWT_SECRET}
app.jwt.expiration=${APP_JWT_EXPIRATION}

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.show-actuator=true

# Logging
logging.level.org.springframework.web=INFO
logging.level.com.example.demo=DEBUG

server.forward-headers-strategy=framework

springdoc.writer-with-default-pretty-printer=true