spring.application.name=task-manager-kanban
spring.profiles.active=prod
springdoc.use-management-port=false
springdoc.swagger-ui.disable-swagger-default-url=true
spring.datasource.hikari.data-source-properties.sslmode=require
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
springdoc.swagger-ui.use-root-path=true
springdoc.api-docs.groups.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=alpha