name: Mantener API Viva

on:
  schedule:
    - cron: '*/14 * * * *'
  workflow_dispatch:

jobs:
  ping-job:
    runs-on: ubuntu-latest
    steps:
      - name: Sending signal to Backend and Database
        run: |
          URL="https://backend-de-la-api-del-gestor-de-tareas.onrender.com/api/public/keep-alive"
          status_code=$(curl -s -o /dev/null -w "%{http_code}" $URL)
          
          echo "Status: $status_code"
          
          if [ "$status_code" -eq 200 ]; then
            echo "Success: Render and Supabase are awake."
          elif [ "$status_code" -eq 404 ]; then
            echo "Error: Endpoint not found. Check your Java code."
          elif [ "$status_code" -eq 000 ]; then
            echo "Error: Connection failed. Render might be starting up."
          else
            echo "Warning: Server responded with code $status_code."
          fi
